### PR TITLE
translations: Use .yaml for .desktop translation

### PR DESCRIPTION
**Pull request by palinek**

### CODE REVIEW

**Comment by stefonarch** [comment]
GTM, merging for testing in weblate.

**Comment by palinek** [comment]
@stefonarch Please, how are you merging the PRs? I see some dumb github email in the commit compared to what is in the original commit:
```
$ git log --graph --all
* commit c8d15e91f9d81031db1cfd3d290a1cd0dc77e285 (HEAD -> master, origin/master, origin/HEAD)
| Author: palinek <palinek@users.noreply.github.com>
| Date:   Fri Nov 20 08:18:04 2020 +0100
| 
|     translations: Use .yaml for .desktop translation (#208)
|   
| * commit 848a32e0817615649664f7bde7f919c46986a1e6 (origin/translations_update, translations_update)
|/  Author: Palo Kisa <palo.kisa@gmail.com>
|   Date:   Fri Nov 20 00:07:38 2020 +0100
|   
|       translations: Use .yaml for .desktop translation
| 
* commit 686bd77c32fe7c196867db82b4486724a03963c2
```

**Comment by stefonarch** [comment]
I use "squash and merge"  button as told by tsujan.
Usually the browser activatesalways  this  button, but could be that I oversee when it doesn't and I created a merge commit by 
mistake, but don't think so.

**Comment by palinek** [comment]
No there is no merge commit in this case. But it created a commit with some dumb github mail.

**Comment by palinek** [comment]
We probably should avoid the web GUI "squash" button.

**Comment by tsujan** [comment]
> We probably should avoid the web GUI "squash" button.

I got suspicious of it after a problem in commit history...

It's the easiest way of merging multiple commits and I don't think we're alone in this.

**Pull request merged**
