### PR TITLE
Update about dialog

### PR DESCRIPTION
**Pull request by shlyakpavel**
99px_ru_wallpaper_6322_strannij_ded_moroz
Happy new year :)

### CODE REVIEW

**Comment by tsujan** [comment]
Once I read about how to update the copyright line (don't have a link now). Some say it's OK to update it; some say it's better to write it as 2018-2020; still others believe that it can be left as it is.

I think 2018-2020 tells about the beginning too.

**Comment by shlyakpavel** [comment]
>  Some say it's OK to update it; some say...

It would be cool if we had a standard for LXQt and we used it everywhere in our projects

**Comment by tsujan** [comment]
I saw this in pcmanfm-qt: Copyright (C) 2009 - 2014 洪任諭 (Hong Jen Yee)

**Comment by shlyakpavel** [comment]
I have a concern that changing the string may break translations.... that won't update in a moment for weblate being down

**Comment by tsujan** [comment]
But lximage-qt says: Copyright (C) 2013

So, yes, a standard would be good.

I use `year-year` in my source files whenever I change them but that's just a habit, not something to be recommended.

> I have a concern that changing the string may break translations

Although I've had similar concerns now and then, I think translations are there to be broken and fixed once in a while ;)

**Comment by shlyakpavel** [comment]
> Let's keep this not merged until others participate :)

**Comment by tsujan** [comment]
> Let's keep this not merged until others participate :)

A discussions can still happen but I assumed it wasn't important to others -- one month was enough. Also, the change was OK.

**Pull request merged**
