### PR TITLE
Support opening and extracting disk images

### PR DESCRIPTION
**Pull request by tsujan**
There are two kinds of disk images, both of which have the mimetype `application/x-raw-disk-image`: compressed and non-compressed. To distinguish between them, the virtual type `compressed-disk-image` is added.

Then, `bsdtar` is used to handle compressed disk images (because `7z` can't open them), while other kinds of disk images are left to `7z`.

Also removed `isoinfo.sh` from cmake because it was redundant: ISO was handled by 7z.

Closes https://github.com/lxqt/lxqt-archiver/issues/171

### CODE REVIEW

**Comment by tsujan** [comment]
This needs more work because `bsdtar` can't handle uncompressed disk images while `7z` can't open compressed ones. So, both of them are needed.

**Comment by tsujan** [comment]
Done!

I don't know whether it's about the difference between GLib and Qt or the bad structure of the core code (inherited from file-roller) but here, I had to add lots of code for what I did with just three lines in Arqiver (https://github.com/tsujan/Arqiver/blob/3ab29862128d462d2a6686cda983b2ce0544b290/backends.cpp#L136).

**Comment by tsujan** [comment]
No one interested in this? It works fine but with a ridiculously large code. Personally, I don't like it because of that but there's no other way either because there are different kind of disk images (file-roller and engrampa fail to open (all of) them).

**Comment by stefonarch** [comment]
Isn't mount iso files (action in pcmanfm-qt) a better option instead of extract them with archiver?
It needs fuseisomount installed.

**Comment by tsujan** [comment]
Here, we're dealing with archives, not with mounting: the user doesn't want to mount anything but to check the contents of the archive.

Moreover, (1) this isn't just about ISO; and (2) pcmanfm-qt and lxqt-archiver aren't related to each other.

**Comment by stefonarch** [comment]
I've nearly never worked with *.iso files, but if the code is written and working why not offer it to users?

**Comment by tsujan** [comment]
> I've nearly never worked with *.iso files

I don't use them often either but I've collected several disk images for testing.

> but when the code is written and working why not offer it to users?

Yes, the code works but is weird. I had to define the "virtual type" `compressed-disk-image`. There's noting similar to it in the rest of the code (or anywhere else, as far as I know). I think that's because the structure of the code isn't flexible enough (actually, IMO, it's terrible) but we've inherited it. Maybe, that's the reason why file-roller can't open most compressed disk images correctly.

It's also possible that I'm denigrating file-roller's code only because I've achieved the same result with a few lines in Arqiver, using Qt. I may have lost my objectivity here; hence hesitating about this patch...

**Comment by tsujan** [comment]
OK, I merge this because it enables lxqt-archiver to do what neither file-roller nor engrampa can and I haven't found a better way. It could be changed later if a shorter method is found.

**Pull request merged**
