### PR TITLE
Support viewing (launching) current item

### PR DESCRIPTION
**Pull request by tsujan**
By double-clicking it or through its context menu item if it's a file.

Also, remember the last dir on opening files in eaach session.

Also, set `Qt::AA_UseHighDpiPixmaps`.

Also, commented out `QDebug` messages to be able to see temporary ones ;)

### CODE REVIEW

**Comment by agaida** [comment]
Works fine for me - but an additional entry "Open with ..." would be nice too. Example: *.svg - one might want to use inkscape or a simple text editor

**Comment by tsujan** [comment]
@agaida What you want is quite valid. Currently, it uses the default app that's assigned to the mime-type. However, when item DND is implemented, the item could be dropped anywhere without further extraction because it's already extracted (in `/tmp` and temporarily).

That being said, I'll think about "Open with ..." later -- not for this PR.

**Comment by tsujan** [comment]
Oh, with the kind of DND I have in mind, the item can be dropped into text editor too -- it's not like engrampa but like Arqiver.

**Comment by agaida** [comment]
I'm fine with - but we should not forget

**Comment by tsujan** [comment]
> but we should not forget

I won't but, for now, there are more important features to implement and bugs to fix. For example, when the header of a 7z archive is encrypted, lxqt-archiver can't open it although it's equipped with the required tools (that may be easy to fix); encrypted files don't have any emblem to show that they're password protected; 7z archives containing files with different passwords aren't well supported; etc.

I think, with the clean code @PCMan has written, no problem should be hard to fix -- I just hope I won't make his code untidy.

**Pull request merged**
