### PR TITLE
Commented out some unused C functions

### PR DESCRIPTION
**Pull request by tsujan**
They weren't used anywhere and their names were so that they might be used for new GLib functions.

Closes https://github.com/lxqt/lxqt-archiver/issues/113

### CODE REVIEW

**Comment by shlyakpavel** [comment]
@tsujan I would just remove these functions instead of commenting them out. No one likes bloated code.

**Comment by tsujan** [comment]
Unlike qps, file-roller code is orderly. They might be useful someday; if so, I'll change their names.

**Comment by tsujan** [comment]
file-roller was written by gnome-2 devs; they had right to use `g_` in function names because they were GLib devs too.

**Comment by shlyakpavel** [comment]
> They might be useful someday

So we can used the functions that are now available in glib

**Comment by tsujan** [comment]
Who knows?

Commented lines don't make a code untidy or hard-to-read, IMHO. Bad code structure does.

**Comment by tsujan** [comment]
@agaida, sorry, I forgot that I'd requested a review from you! It was needed for git users and was checked by 3 testers (me included).

**Pull request merged**
