### PR TITLE
Open Recent menu

### PR DESCRIPTION
**Pull request by krab**
Here is support for open recent files in Gui.

No idea how to get file name (baseName) code from path.
```
        //fixme wtf is this?
        QString name = QString::fromUtf8(Fm::FilePath::fromUri(QUrl(path).toEncoded().constData()).baseName().get());
```
Original idea was to use `QHash<QString, QVariant>` to store path as a key and fileName as value. To avoid using QFileInfo for file names. As QFileInfo will basically wake up parked/slow hard drives and do unnecessary network filesystems requests.

But still retrieving file name from path on every program start is a bad idea, for example local/network filesystem can be not mounted at all. I give up on qhash because in qt 5.15 they deprecated backward itterator https://doc.qt.io/qt-5/qhashiterator-obsolete.html

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks for trying to make lxqt-archiver better.

I don't think lxqt-archiver needs "Recent Files". IMHO, we need to resist the temptation of adding options for the sake of adding options; otherwise, we'll clutter the GUI and confuse the user, so say nothing of more resource usage.

You could first propose your changes by opening a report and start to implement them if they're accepted.

Anyway, a "Recent Files" menu should have several properties. See https://github.com/lxqt/pcmanfm-qt/commit/a5f5e1ce3fced2257799fe9b77ad6e5a2bfd86c2 for an example.

**Comment by krab** [comment]
Engrampa has option for recent files https://i.imgur.com/YtE4T9R.png

Acquiring file information on every application startup just to retrieve file name will cause hardware/network IO and won't work properly on unmounted filesystems and will freeze Gui on parked HDD wakeups or "disk sleep" state on slow IOPS ssds.

**Comment by tsujan** [comment]
> Engrampa has option for recent files

The goal hasn't been recreating Engrampa's GUI in Qt.

**Comment by krab** [comment]
Then idea was to make lxqt utilities have bad UI/UX? And worse than kde equivalents on purpose?

**Comment by tsujan** [comment]
I just mean the we need to be more careful when adding features. KDE adds features without checking whether they clutter the GUI or add to the resource usage; we don't do that in LXQt.

**Comment by tsujan** [comment]
These are among LXQt's criteria:

 * Simple GUIs (but not too simple).
 * Enough options (but not too many).
 * Lightness.
 * Clean codes.

**Pull request closed without merging**
