### PR TITLE
Fix typo in CHANGELOG

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by tsujan** [comment]
It's late. I released it.

**Comment by jubalh** [comment]
I know. It doesn't matter for this release. In the tarballs we will just have it wrong. But for the next one it will be fixed.

**Comment by tsujan** [comment]
> But for the next one it will be fixed.

Yes.

**Comment by tsujan** [comment]
BTW, I saw lots of typos in Alf's old changelogs but didn't correct them -- weren't worth the effort. However, it's good to have clean changelogs.

**Pull request merged**
