### PR TITLE
Updated to new mimetype names of shared-mime-info ≥ 2.3

### PR DESCRIPTION
**Pull request by tsujan**
They are `application/vnd.efi.iso`, `application/vnd.efi.img`, `application/x-bzip2` and `application/x-bzip2-compressed-tar`.

### CODE REVIEW

**Comment by tsujan** [comment]
Any objection to merging this?

I think I'm the only one who has tested it. Apart from bzip2 files, its test requires having `application/vnd.efi.iso` and `application/vnd.efi.img` files (with extensions `.iso` and `.img`), and I'm not sure they're easily accessible (I had them for testing Arqiver).

**Comment by stefonarch** [comment]
Archiving is not my area, testing this with` .img` and `.iso` I get "type of archive not supported".

**Comment by tsujan** [comment]
> testing this with .img and .iso I get "type of archive not supported"

They're supported — not for archiving but for opening.

**Comment by tsujan** [comment]
OK, if this simple patch explodes anyone's computer, I'll take responsibility and say, "Sorry!" (nothing more).

**Comment by Bluey26** [comment]
Hello.

Today i have seen the new `lxqt-archiver` package in archlinux packages (lxqt-archiver 0.9.1-1).
Unfortunately i still have the same issue with the .bz2 files, they dont have the 'extract to..' and 'extract here' actions unless i use the custom actions mentioned in https://github.com/lxqt/libfm-qt/issues/938 .

An example .tar.bz2 file can be found in here: http://downloads.sourceforge.net/smplayer/smplayer-themes-20.11.0.tar.bz2 (smplayer themes file, taken from https://www.smplayer.info/en/downloads).

I have restarted the desktop module in Session settings and even restarted the computer, with no luck.

Do i also have to update some other package like `libfm-qt6` for this to work? (I have seen that libfm-qt6 has not changed in a few weeks, so it was just an example package which could be related).

I have  `shared-mime-info 2.4-1` and the system is up to date.

**Comment by tsujan** [comment]
> they dont have the 'extract to..' and 'extract here' 

That's because `/usr/share/libfm-qt/archivers.list` hasn't been changed — and we don't have a plan to update it because the next version of libfm-qt is based on Qt6.

You can replace what comes after `mime_types=` inside `/usr/share/libfm-qt/archivers.list` with what comes after `MimeType=` in `/usr/share/applications/lxqt-archiver.desktop` (but don't change `mime_types=` itself). Then restart pcmanfm-qt.

**Comment by Bluey26** [comment]
**UPDATE**: adding `application/x-bzip2-compressed-tar;`  to the` mime_types=` section under `[lxqt-archiver]` section in `/usr/share/libfm-qt/archivers.list` and restarting the desktop session module, makes 'Extract to..' and 'Extract here' options to appear properly in the` .tar.bz2` file (they appeared even when i deleted the custom actions, so this seems to work).

I think that the same 'update' to the mime formats should be made in `archivers.list`

**Comment by tsujan** [comment]
Of course, if you  use `libfm-qt6`, you'll need to do the same thing with `/usr/share/libfm-qt6/archivers.list`, but that file will be updated soon.

**Comment by Bluey26** [comment]
Oh, i have not seen you previous comment ^^ (it was the same thing i did)

Yes, i have modified it myself, and its working now, since you say it will be added in the libfm-qt6 file, there is nothing more to do :)

**Comment by tsujan** [comment]
> since you say it will be added in the libfm-qt6 file...

Will do it for lxqt-archiver and arqiver, which are already updated to the new MIME type strings..

If you know of another listed archive manager which is also updated, please tell us.

**Pull request merged**
