### PR TITLE
Qt6 port

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by Chiitoo** [comment]
Heh.  Been meaning to see if I could do this one, but didn't quite get to it!

In any case, seems to work fine so far for me, but I had to adjust some include file paths due to, for example:

```
/source/path/src/archiver.h:7:10: fatal error: libfm-qt/core/filepath.h: No such file or directory
    7 | #include <libfm-qt/core/filepath.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

My packaging things is still a work in progress though, so maybe it's something for me to adjust, but currently these go under `/usr/include/libfm-qt6/` so had to add the '6' to a bunch of include lines.

**Comment by tsujan** [comment]
@Chiitoo, thanks a lot! It's my silly mistake; correcting it....

**Comment by tsujan** [comment]
@Chiitoo 
I corrected the headers. Would you please test again?

**Comment by Chiitoo** [comment]
Mystery headers.  : ]

Works all good now here too.

Thank you!

**Comment by tsujan** [comment]
> Works all good now here too.

Thanks!

> Mystery headers. : ]

I still don't know how I was able to compile it with those wrong headers! Investigating later....

**Comment by tsujan** [comment]
Please also report any problem you might encounter when compiling other components! Always assume that the issues are ours, not yours.

**Comment by stefonarch** [comment]
Me too compiled without issues with the old headers.

**Comment by tsujan** [comment]
> Me too compiled without issues with the old headers.

Although the problem is fixed, something is different in the case of lxqt-archiver. It may be in front of my eyes, but I don't see it yet ;)

**Comment by Chiitoo** [comment]
I suppose one explanation could be having a qt5 build of `libfm-qt` installed too?

And yeah, will of course report things as per the usual, though things tend to work so well that there's not much to make a report out of.

**Comment by tsujan** [comment]
> I suppose one explanation could be having a qt5 build of libfm-qt installed too?

Yes, but the compilation should have still failed.

**Comment by stefonarch** [comment]
GTM

**Pull request merged**
